[package]
name = "lfr-hir-def"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lfr-base-db = { path = "../lfr-base-db" }
lfr-vfs = { path = "../lfr-vfs" }