use_field_init_shorthand = true
use_try_shorthand = true
max_width = 80
edition = "2021"
fn_call_width = 40

unstable_features = true
comment_width = 100
brace_style = "AlwaysNextLine"
control_brace_style = "ClosingNextLine"
enum_discrim_align_threshold = 30
fn_single_line = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "Vertical"
indent_style = "Visual"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 30
# trailing_comma = "Always" # temporarely disabled due to https://github.com/rust-lang/rustfmt/issues/5066
trailing_semicolon = false
version = "Two"
wrap_comments = true
